language: python
python:
- '2.7'
- '3.5'
install: pip install -r requirements.txt
script: python -m unittest discover
before_deploy:
- sudo apt-get install pandoc
- pip install pypandoc
deploy:
  skip_cleanup: true
  provider: pypi
  user: gugahoi
  password:
    secure: oqkiUZKFssvUOV+lQQsaT6WJ0EdHcF+fiBoJ0pK2gpE/D5Ty4Em0JNOSaIkj2ID/qqqIeqwU/Grkj6cmjBaah6r6VZ5o0EzltTEAg6XOu5hKbtf3+2pr0c4fA+iF8ZDt34CjM7+GxsDx5yKmTzTDdX0FcvaK4bkFVSsW5en3BuvDTYjqL7fW/1S0G29BX/58F9fe6XLxNlexSkCsGkQJi71q79D59XGhvHMxQbJFqwEnVAushxyjUvYdx2KDV6L5GgaZpD54j/Ga/jHjsXnwXAk+tc0WaVHbFJb7tiG9RvOsHytMGmZFqeMdE4iFs0OX1V5Q0lWGVXsxR9pKEbFGu+EXLGR55wyt7hY2Ugnt0oHNSFjW2ooZLvEIVcj+2aetwuOHK0bOO/NyYoh01jURxddeNTbbBWjICNPzaX48MRoiR0rMFk28PsbQf8I0foPqqwAqBb8k0hXDjg93UGfSvycQC8r5mjLhw8cLDFybaqwB0MqXTlQRWmKdOrH0IBEzhyBoQ6KrbOBq4xaZ/cqA6WdrQwzGNpkqrSZXta2+ictOXfLND3K7/2Q5xVyaWPqk86nj6MrcdwxpRcrXoUqIGXx9NsqGqf3AfQtgo2PhJbL67Lj/VBt3WuesYe+pPZWVsEi3Oli6qFlkM2HAleF9IsCfeUHSf2FlDa46FK89UiE=
  on:
    tags: true
    repo: gugahoi/artifactory_python
