language: python
python:
- '2.7'
- '3.5'
install: pip install -r requirements.txt
script: python -m unittest discover
before_deploy:
- sudo apt-get install pandoc
- pip install pypandoc
deploy:
  skip_cleanup: true
  provider: pypi
  user: gugahoi
  password:
    secure: RKM18XsRn5TRKyflhNKZbJtCMFQ5vkQxVZmAQVTX+80ibh+llEBeTQ6lrDTWiBtu1L0bC0rB5LG7Kge0nGMI7flOgjbcxVLr1Z2ki6Azeu75sTBw+otLJsZh/bsEOtHouPMxdTu/G7Pj5i0OGdty+Y8dmFBaeTi3mjN28t4JtWbCxE/7skw+L7oW6tsb+P5AmnnCHI1mxrXO1552xynW4aGytPV6d/xcD7MYTUUAm/9aan/AwrH4oGXCueWmyHvGBxyE+V/mzoiYjrbsZzmjqGNvtZ3yd8xBvEYTvqo8g+8OOFOcyUXLAHN7Z+N/qHSvNi/QVPvyVIVxYEW+PAHPfv20NxOO1HX0Bc0EHKwCH2lpNNy0myBIni+BO4Bl29cxMsO+68mqBbBqSAFKedJ2Kicwlb3aDm9CvG9lCopYq8iPeyCVo1bSBoKScIGNiaBKX7HyZzNg6GAHDfkErm86T9mNdQR1RpgGFxmHWCy/3m0IXO/kZ8V+yMxSyQ8uzZ6Hbip5HrxszzxqLkfrW9spnrmxBzjrQ3r84BUld8cba7Vei4U5lwnSbUJWHsxXcd8+X2mAU6aLJ8Nf/Sh6Og9FuQFDETXCWMgwOmef59DifZk0jmMCFkT8P7YU8RCsN6JYeFC3ocJUOWAhDjJfPXvWi9iuPkP11Z8nrPsiGBZ+Lw8=
  on:
    tags: true
    repo: MYOB-Technology/artifactory-lib
