steps:
  - label: 'Testing :python:'
    command: 'python -m unittest discover'
    agents:
      queue: 'voyager'
    env:
      BUILDKITE_DOCKER: true

  - label: 'Deploying to PyPi'
    command: ./deploy.sh
    agents:
      queue: 'voyager'
